Repository openshift/tektoncd-pipeline, pull requests merged in 2019-04, with the labels that each got.

#8 Update to use OCP 4
  openshift/ci-operator/Dockerfile-git.in
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/knative-images/bash/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/entrypoint/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/knative-images/gsutil/Dockerfile
  openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/e2e-tests-openshift.sh
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/pipelinerun_test.go
Labels: lgtm, size/L

#10 CI was here
  ci
  examples/taskruns/private-taskrun.yaml
  examples/taskruns/taskrun-docker-basic.yaml
  openshift/e2e-tests-openshift.sh
  test/helm_task_test.go
  test/kaniko_task_test.go
  test/ko_test.go
  test/pipelinerun_test.go
Labels: approved, lgtm, size/L

#13 Reformat code according to shfmt
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#17 First image port to UBI 8
  openshift/ci-operator/Dockerfile-git.in
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/knative-images/bash/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/entrypoint/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/knative-images/gsutil/Dockerfile
  openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/e2e-tests-openshift.sh
  tekton/ko/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#19 More approvers review
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#20 Merge change to master
  Makefile
  openshift/ci-operator/Dockerfile-git.in
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/uidwrapper
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#21 Resolves - https://jira.coreos.com/browse/SRVKP-30
  openshift/ci-operator/Dockerfile-git.in
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/knative-images/bash/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/entrypoint/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/knative-images/gsutil/Dockerfile
  openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#25 Update README to 0.3.0
  README.md
Labels: approved, lgtm, size/XS

#24 CI was here
  ci
Labels: approved, lgtm, size/XS

#27 Update README for 0.3.1 release
  README.md
Labels: approved, lgtm, size/XS

#26 CI was here
  ci
Labels: approved, lgtm, size/XS
