Repository openshift/tektoncd-pipeline, pull requests merged in 2019-07, with the labels that each got.

#81 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#82 Run E2E script with -e
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#88 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#89 Add pullrequest-init image
  Makefile
  openshift/ci-operator/knative-images/pullrequest-init/Dockerfile
Labels: approved, lgtm, size/XS

#90 Add pullrequest-init image
  Makefile
  openshift/ci-operator/knative-images/pullrequest-init/Dockerfile
Labels: approved, lgtm, size/XS

#93 Sync master with latest commit
  Makefile
Labels: approved, size/M

#95 Make snippet compatible with bash also
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/XS

#94 CI was here
  ci
Labels: approved, lgtm, ok-to-test, size/XS

#102 Add v0.5.2 link to Readme and Update Release Readme
  README.md
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/S

#101 Release file for v0.5.2
  openshift/release/tektoncd-pipeline-v0.5.2.yaml
Labels: approved, lgtm, size/XL
