Repository openshift/tektoncd-pipeline, pull requests merged in 2019-12, with the labels that each got.

#248 Readd nop and move knative-images to tekton-images
  Makefile
  openshift/ci-operator/tekton-images/controller/Dockerfile
  openshift/ci-operator/tekton-images/creds-init/Dockerfile
  openshift/ci-operator/tekton-images/entrypoint/Dockerfile
  openshift/ci-operator/tekton-images/gcs-fetcher/Dockerfile
  openshift/ci-operator/tekton-images/git-init/Dockerfile
  openshift/ci-operator/tekton-images/imagedigestexporter/Dockerfile
  openshift/ci-operator/tekton-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/tekton-images/nop/Dockerfile
  openshift/ci-operator/tekton-images/pullrequest-init/Dockerfile
  openshift/ci-operator/tekton-images/webhook/Dockerfile
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/M

#249 Fix the nop hack
  openshift/ci-operator/tekton-images/nop/Dockerfile
Labels: approved, lgtm, size/XS

#251 Never understimate the power of a hack
  openshift/ci-operator/tekton-images/nop/Dockerfile
Labels: approved, lgtm, size/XS

#246 Releasing release.yaml v0.9.0
  openshift/release/tektoncd-pipeline-v0.9.0.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XL

#253 Fix trianon => tianon 🤦‍♀️
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/XS

#252 Fix 0.9.0 release, moving to tekton-images/ and using our own nop image instead of external
  Makefile
  openshift/ci-operator/tekton-images/controller/Dockerfile
  openshift/ci-operator/tekton-images/creds-init/Dockerfile
  openshift/ci-operator/tekton-images/entrypoint/Dockerfile
  openshift/ci-operator/tekton-images/gcs-fetcher/Dockerfile
  openshift/ci-operator/tekton-images/git-init/Dockerfile
  openshift/ci-operator/tekton-images/imagedigestexporter/Dockerfile
  openshift/ci-operator/tekton-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/tekton-images/nop/Dockerfile
  openshift/ci-operator/tekton-images/pullrequest-init/Dockerfile
  openshift/ci-operator/tekton-images/webhook/Dockerfile
  openshift/release/tektoncd-pipeline-v0.9.0.yaml
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/M

#247 Update RELEASE_PROCESS with latest
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/M

#254 Switch busybox images to UBI
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/M

#261 Add 0.9.0 and 0.9.1
  README.md
Labels: approved, lgtm, size/XS

#260 Releasing release.yaml v0.9.1
  openshift/release/tektoncd-pipeline-v0.9.1.yaml
Labels: approved, lgtm, size/XL

#265 0.9.2 and update a bit the release process to make it quicker
  README.md
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/M

#264 Releasing release.yaml v0.9.2
  openshift/release/tektoncd-pipeline-v0.9.2.yaml
Labels: approved, lgtm, size/XL

#268 Bump golang to 1.13
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#266 Modify the RELEASE PROCESS to add catalog tagging in there
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/M

#272 Add pipeline-catalog release process
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/S
