Repository openshift/tektoncd-pipeline, pull requests merged in 2019-10, with the labels that each got.

#148 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#150 Use ubi-minmal for docker images
  Makefile
  openshift/ci-operator/Dockerfile-git.in
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/generate-dockerfiles.sh
  openshift/ci-operator/knative-images/bash/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/entrypoint/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/knative-images/gsutil/Dockerfile
  openshift/ci-operator/knative-images/imagedigestexporter/Dockerfile
  openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/ci-operator/knative-images/pullrequest-init/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
Labels: approved, size/M

#153 Fix typo in Makefile
  Makefile
Labels: size/XS

#154 Add info about how to add a new binary/image
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/S

#157 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#158 Improves Release Process Documentation
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/XS

#161 Improve resolve-yamls.sh
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/XS

#166 Improve Release documentation
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/XS

#168 Add link to release-0.7.0 👼
  README.md
Labels: approved, lgtm, size/XS

#162 Add v0.7.0 release.yaml
  openshift/release/tektoncd-pipeline-v0.7.0.yaml
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/XL

#172 Add mechanism to build/tag gcs-fetcher image which is used by tekton-controller
  Makefile
  openshift/ci-operator/knative-images/gcs-fetcher/Dockerfile
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/S

#173 Improve Makefile
  Makefile
Labels: approved, lgtm, size/XS

#174 Patch for build/tag gcs-fetcher image
  Makefile
  openshift/ci-operator/knative-images/gcs-fetcher/Dockerfile
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/S

#176 Add v0.7.0 release.yaml
  openshift/release/tektoncd-pipeline-v0.7.0.yaml
Labels: approved, lgtm, size/XS

#151 Adds OpenShift monitoring config
  openshift/addons/pipeline-monitoring.yaml
  openshift/e2e-tests-openshift.sh
  openshift/release/generate-release.sh
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/M

#193 Updates readme for release v0.8.0
  README.md
Labels: approved, lgtm, size/XS

#199 Add nightly tektoncd-pipeline
  Makefile
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/S

#202 Fix syntax error in check-image target
  Makefile
Labels: approved, lgtm, size/XS

#203 Ensure release-next does not track upstream/master
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XS

#192 Adds tekton pipelines 0.8.0 release.yaml
  openshift/release/tektoncd-pipeline-v0.8.0.yaml
Labels: approved, lgtm, size/XL

#207 Remove bash and check removed images
  Makefile
  openshift/ci-operator/knative-images/bash/Dockerfile
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/S
