Repository openshift/tektoncd-pipeline, pull requests merged in 2019-09, with the labels that each got.

#129 Adds metrics configuration to pipeline
  RELEASE_PROCESS.md
  openshift/release/generate-release.sh
Labels: approved, lgtm, size/XS

#130 Rekick job so it can pick up the pullrequest-init image
  ci
Labels: approved, lgtm, size/XS

#136 Use upstream nop image to fix sidecar tests.
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#137 Fix check-images target
  Makefile
Labels: approved, lgtm, size/M

#139 Fixes for CI Breakage due to upstream example modifications
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#145 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#147 Don't use upstream image for nop, but....
  Makefile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/e2e-tests-openshift.sh
Labels: size/S
