Repository openshift/tektoncd-pipeline, pull requests merged in 2019-05, with the labels that each got.

#28 Add Release Process
  README.md
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/M

#29 Update update-to-head.sh to latest version
  Makefile
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: approved, size/M

#31 Update e2e script to mirror upstream changes
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#33 Add GitHub repo name to hub command and fail fast
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XS

#35 Update base images to UBI8 GA
  openshift/ci-operator/Dockerfile-git.in
  openshift/ci-operator/Dockerfile.in
  openshift/ci-operator/knative-images/bash/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/creds-init/Dockerfile
  openshift/ci-operator/knative-images/entrypoint/Dockerfile
  openshift/ci-operator/knative-images/git-init/Dockerfile
  openshift/ci-operator/knative-images/gsutil/Dockerfile
  openshift/ci-operator/knative-images/kubeconfigwriter/Dockerfile
  openshift/ci-operator/knative-images/nop/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#37 Downstream release 0.4.0 CI setup
  Makefile
  openshift/ci-operator/knative-images/imagedigestexporter/Dockerfile
Labels: approved, lgtm, size/XS

#41 Update documentation with some nits and bits
  RELEASE_PROCESS.md
Labels: approved, lgtm, size/S

#40 Build gsutil image with CI
  ci
Labels: approved, lgtm, size/XS

#38 Add makefile target to pull images from CI and push to quay
  Makefile
Labels: approved, lgtm, size/S
