Repository openshift/tektoncd-pipeline, pull requests merged in 2020-01, with the labels that each got.

#276 Fix extra-space in resolved yaml manifest
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/XS

#282 Add ubi based gs-util image
  openshift/ci-operator/tekton-images/gs-utils/Dockerfile
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/S

#292 Remove extra space
  openshift/release/tektoncd-pipeline-v0.9.2.yaml
  openshift/resolve-yamls.sh
Labels: approved, lgtm, size/S

#293 Make sure we compile the binary statically
  Makefile
Labels: approved, lgtm, size/XS

#296 Adds no-ci and cloud-event to ingore list
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#300 Add disable_gcp build tag to make it run on GCP 🏃
  Makefile
Labels: approved, lgtm, size/XS

#302 Fix Command to disable_gcp
  Makefile
Labels: approved, lgtm, size/XS

#310 Releasing release.yaml v0.10.0
  openshift/release/tektoncd-pipeline-v0.10.0.yaml
Labels: approved, lgtm, size/XL

#314 Releasing release.yaml v0.10.1
  openshift/release/tektoncd-pipeline-v0.10.1.yaml
Labels: approved, lgtm, size/XL
